Pill neutral
estenp/token-test pull request #84
Opened 2023-07-13 14:37 UTC by lxm6938amount

Updating neutral pill component

2023-07-21 21:04 UTC, estenp commented
@JohnathanHuggett @pragati-amount Are we ok with this variant names in terms of how they will be used as variant prop to the Pill component?
e.g.
`variant="info-outlined"`

2023-07-21 21:10 UTC, estenp approved these changes

2023-07-21 21:10 UTC, estenp commented on tokens/apex/components/unrestricted/pill/counterAttention.json
> +{
@pragati-amount @JohnathanHuggett  I don't think these "counter" variants are able to be achieved within the Pill component's constraints, and I'm not sure exactly what they are.

I had to fix Liam's initial JSON to use Pill token constraints, so they are likely not achieving design with these tokens.

We need to either ensure they are styled using valid Pill tokens in Figma or remove these as Pill variants and audit this as it's own component.

2023-07-25 20:24 UTC, JohnathanHuggett commented
> @JohnathanHuggett @pragati-amount Are we ok with this variant names in terms of how they will be used as variant prop to the Pill component? e.g. `variant="info-outlined"`

Yes that seems good

2023-07-25 20:26 UTC, JohnathanHuggett approved these changes

2023-07-25 20:26 UTC, JohnathanHuggett commented on tokens/apex/components/unrestricted/pill/counterAttention.json
> +{
All these should be removed. They are being explored. I am having @pragati-amount remove them from the pills file

2023-07-26 14:09 UTC, JohnathanHuggett requested changes
need to remove the counter variants

2023-07-26 14:18 UTC, JohnathanHuggett approved these changes

2023-07-26 14:18 UTC, merged